name: simple github action
on: push 
branches:
         -main
jobs:
      Say Hello
      runs-on: ubantu-latest
        steps:
          -name: cheak the code
           run: actions/cheakout@v3
          -name: Say Hello
           run: echo "hello from github action"
         
    
